apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
  labels:
    app: affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: pause
    image: gcr.io/google-containers/pause:3.6
