apiVersion: v1
kind: Pod
metadata:
  name: echo-sidecar
spec:
  containers:
  - name: app
    image: hashicorp/http-echo
    args: ["-text=Hello"]
  - name: log-shipper
    image: busybox
    command: ["sh", "-c", "tail -n+1 -F /var/log/app.log"]
